// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxcweqarvcphudzaejcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Y3dlcWFydmNwaHVkemFlamNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NzQzMjgsImV4cCI6MjA1MTA1MDMyOH0.qqttSddvhXALS0Pibyd6eQHuy_eMPIkGPWszknPKR2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);